### ISSUE TITLE
Few questions about the loss function and paper

### ISSUE THREAD

**Issue by FlyingRoastDuck** [CompVis/vunet#17]
Hi:
I have few questions about the implemention of loss function and your paper. 
1. In [main.py](https://github.com/CompVis/vunet/blob/master/main.py#L206) and [main.py](https://github.com/CompVis/vunet/blob/master/main.py#L223) you seems to minimize the proposed loss. However, you claim to maximize the Eq.5 in your paper. The form of proposed loss is also changed. You seem to add KL divergence to the final loss function rather than minus it.  Could you please explain it?

2. The network E is employed to estimate the mean of P(z|y_hat), a distribution correlated to z, so what's the specific meaning of concatinating E(x) and z~q(z|x,y_hat) and send it to D to obtain P(z|x,y_hat)? E(x) seems to have stronger relationship with z than y_hat.

Thank you.

**Comment by pesser** [comment]
Hi,

1. Yes, that is a horrible typo in the paper, sorry about that and thanks for letting us know! I'll try to fix it asap. Problems start in eq. 3 of the paper, where the minus must be on the likelihood term and not the KL term (because we want to maximize the data likelihood <-> minimize the negative likelihood). In eq. 4 the sign of the likelihood term somehow got fixed but not the one on KL and the same is true for eq. 5. To summarize: Eq. 3 should be +KL and -likelihood, eq. 4 should be +KL and +l1 term and same for eq. 5 it should be  +KL and +the sum of l1 terms. Sorry again. The implementation is correct. The final loss function is derived from the ELBO in eq. 2 but on the way to eq. 5 things got messed up probably due to the switch from maximization to minimization.
2. The main purpose of the network E is to provide a good shape representation on multiple scales via skip connections to the decoder D. At the same time we reuse it to estimate a prior for the appearance distribution. This just makes less assumptions about the data, but you could also specify a constant prior, e.g. a standard normal distribution. In our experiments both settings worked fine and in fact I prefer the latter variant now. The concatenation is just another skip connection from E to D. Note that one must be careful when talking about E(x) - due to the skip connections it has many "outputs". Early layers with high resolution will be correlated mainly with the shape y_hat but closer to the bottleneck it can learn a certain bias between shape and appearance - the canonical example being that a shape depicting a sports scene results in reduced likelihood for an appearance of a person wearing a business outfit. But as noted above this is quite a nuanced detail and like I said, a fixed prior for appearance works great, too! I encourage you to try it.

Hope that clarifies things a bit.
Best
Patrick

**Comment by FlyingRoastDuck** [comment]
Thank you. You've been very helpful.
