### ISSUE TITLE
hey why can't I use vunet in tf ver over 12

### ISSUE THREAD

**Issue by richard0326** [CompVis/vunet#18]
hey why can't I use vunet in tf ver over 12??
First thing I'm not only using vunet. So I have a situation to use tf ver over 12.
I tried your open source and have found some problem in nn.py conv2d func.
it stops in con2d func. what is the problem???

it works but when its 'enc_up' func's iterator l is in 3.
it stops in con2d func. and stops in 

```
g = tf.get_variable('g', dtype=tf.float32, initializer = scale_init)
b = tf.get_variable('b', dtype=tf.float32, initializer = -m_init * scale_init)
```

this code.
and I don't understand. why it stops here

**Comment by pesser** [comment]
Hi,
[The problem](https://github.com/tensorflow/tensorflow/issues/12598) is related to the data dependent initialization. I pushed a [tf13compat branch](https://github.com/CompVis/vunet/tree/tf13compat) which should work with all versions of tensorflow. Would be super nice if you could let me know if everything works as expected since I cannot test it exhaustively atm.

Best
Patrick

**Comment by richard0326** [comment]
thanks! I have changed your open source code in my way. But not working like the paper.
So I'm gonna try your new code.
I will let you know how good it works.
