### ISSUE TITLE
Please share pretrained model

### ISSUE THREAD

**Issue by ishandutta2007** [CompVis/vunet#20]
As I can see it was requested before too but the issue has been closed without providing one. If it's going to be provided while CVPR please let the issues remain opened

**Comment by pesser** [comment]
Due to popular request you can now find code and checkpoints of the original models in [the runs subdirectory of the data page](http://129.206.117.181:8080/runs/). But please keep in mind that the code is quite messy and I cannot provide further support for it. The checkpoints found there are not compatible with the graphs defined in this repository, so they must be used with the code that comes with them.

I have started training models for [the branch supporting tensorflow >= 1.3](https://github.com/CompVis/vunet/tree/tf13compat) and will upload them once they are finished (~ a week?).

Best
Patrick

**Comment by ishandutta2007** [comment]
Thanks Patrick, move it to drive/dropbox once done, hosting it on one lone server is not convenient.

**Comment by pesser** [comment]
[Done](http://129.206.117.181:8080/pretrained_checkpoints/). Also, `master` merged the changes to support tensorflow >= 1.3. I'm still looking for a good hosting option (I don't like the option of cluttering my gdrive/dropbox plus I always find it super annoying that I can not simply `wget` from from drive - not sure about dropbox though?). Until then, the current server will have to do.

**Comment by ishandutta2007** [comment]
I guess the best idea is to just create a new email a/c with name of the repo and put it in it's drive , that way you don't end up cluttering your personal drive.

**Comment by pesser** [comment]
Right, thanks! But now I already found a [long-term solution](https://heibox.uni-heidelberg.de/d/71842715a8/) with our university's storage service.
