### ISSUE TITLE
About IS and SSIM

### ISSUE THREAD

**Issue by heerduo** [CompVis/vunet#29]
I have a question about calculating SSIM and IS which are shown in "section 4.1. Image reconstruction".
I can not find the algorithm for calculating these scores in code, and the result of these in experimental results.
So I want to ask you about this.

Looking forward to your reply.

**Comment by pesser** [comment]
Since my coauthor ran that experiment I cannot tell you precisely which implementation was used in that case. The classical implementation is provided by [OpenAI](https://github.com/openai/improved-gan) but it is not without issues. `tf.contrib` also includes a little [GAN library](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/gan) now, which has an improved implementation. Both `scikit-image` and `tensorflow` provide implementations of SSIM.
I think [FID](https://arxiv.org/pdf/1706.08500.pdf) should be preferred now.

**Comment by ChenCherry** [comment]
Thanks a lot.
