### ISSUE TITLE
KL divergence Problem in models.py #L217

### ISSUE THREAD

**Issue by FlyingRoastDuck** [CompVis/vunet#4]
Hi, I have a question about the code  
[model.py](https://github.com/CompVis/vunet/blob/master/models.py#L217)
It seems that you compute MSE of the 2 distributions rather than KL divergence ,which is different from your published paper.  
Is that for special reason？

**Comment by pesser** [comment]
Hi,
the KL divergence between two Gaussians of _fixed covariance_ is equal to the squared distance between their means (up to a constant) - which is what we compute. Thus we do compute the KL divergence but we also model the distributions as Gaussians with identity covariances (implying a euclidean distance) and estimate only the mean. The reason is simply that we found this to be more stable (especially when combined with very small weights for the KL term which we use in the beginning of training) without restricting the model too much.
Best
Patrick

**Comment by FlyingRoastDuck** [comment]
Thank you , you've been very helpful
