### ISSUE TITLE
Code Collapse problem

### ISSUE THREAD

**Issue by Harry-Zhi** [CompVis/vunet#5]
Hi,

Many thanks for the cool paper and idea.

I am wondering when you train the variational U-net end to end, did you meet the code collapse situation where KL loss are easily to become 0 in early training stage so many codes are inactive.

Since when I play-around with the variational U-net (adding more layers, change activation function), my training is not stable and quickly makes the code inactive.

I am thinking since we have skip layers which may convey strong information so the decoder may neglects the code?

Could you share some advice on training this kind of deep VAE so that we can avoid code collapse to have a meaningful code.

Many Thanks.

**Comment by pesser** [comment]
Hi,
Collapsed encodings are indeed a problem we have observed. To avoid it, we start with a weight of nearly zero for the KL loss (thus disabling it) and only start to increase it after 50k training iterations (see code below). Even without the KL loss it takes quite a while until the network starts to use information through the encoding (as you have observed, due to the skip connections the decoder first tries to utilize them as good as possible and only slowly discovers missing information through the other encoding). I'd suggest always starting without the KL loss and only introducing it once the encoding contains too much information such that the transfer task does not work anymore.
Best
Patrick

https://github.com/CompVis/vunet/blob/f0d6ef73b02e6099d3b5e4f37e4ddaaa5f8437e6/main.py#L156

**Comment by Harry-Zhi** [comment]
@pesser 
Hi Patrick, many thanks for your explanation.

I see the coco training config of your training, as you said, you begin to increase the KL weight from 1e-6 to 1 starting at 50000 iterations and finish increasing LK weight at 75000 iterations.

Based on this ,I have an extra question. **How did you inspect the training process to make sure that the code is used during the training.**

What values are good indicators for this?

Currently, I can only come up with an idea that I could keep looking the Kl loss, when I have a non zero KL weight, I would expect that KL loss does not decrease to 0. But I do not think it is a good practical way to inspect the collapse situation.

By the way, when we have 0 Kl loss weight, you only train the network by the reconstruction loss. 
I am curious, at this time (Kl loss == 0), do we still need to sample from the latent code for the decode or should we, for example,  just pass the mean value from the encoder to the decoder so that it behaves as a deterministic auto-encoder. **I am not sure whether both of these are correct.**
 
In your code, it seems when you block the KL loss in the total loss, you still do a sampling operation from the mean and std generated by encoder.

Could you please comment on this?

Many thanks for your patient help.
Best,
Shuaifeng

**Comment by pesser** [comment]
> How did you inspect the training process to make sure that the code is used during the training.

If you look at Figure 9 of our paper the first row shows what happens when the network does not use the appearance code at all. Without the appearance code, the network can not, among other things, figure out what colors to produce and therefore always produces averaged colors - typically resulting in gray colors. Thus, colors are a good qualitative indicator that the code is used (as long as the network is not completely overfitting).

> when we have 0 Kl loss weight [...] do we still need to sample from the latent code for the decode or should we, for example, just pass the mean value from the encoder to the decoder so that it behaves as a deterministic auto-encoder

There are different options here. In case of zero kl weight we found that things become instable if we also predict the variance, so this is actually part of the reason we only estimate the mean of the distribution (see #4). In this setting we do not find it necessary to disable sampling. Note that since the stddev of the added noise is now constant,

https://github.com/CompVis/vunet/blob/f0d6ef73b02e6099d3b5e4f37e4ddaaa5f8437e6/models.py#L212

the network can simply increase the magnitude of the estimated mean (since the kl weight is zero/small) until that noise becomes irrelevant. If you really want to reduce the behaviour to an autoencoder at zero kl weight, I'd suggest to adapt the sampling with the kl weight, i.e. something like

    return mean + kl_weight * stddev * eps

where eps is normal noise.

I'm closing here, since this is not really an issue related to the code, but feel free to write me an email to continue the conversation!
Best
Patrick
